export const ACTION = {
  INIT: 'INIT',
  MOVE_NORTH: 'MOVE_NORTH',
  MOVE_SOUTH: 'MOVE_SOUTH',
  MOVE_EAST: 'MOVE_EAST',
  MOVE_WEST: 'MOVE_WEST',
  CONFIRM: 'CONFIRM',
  CANCEL: 'CANCEL',
  ANY_KEY: 'ANY_KEY',
  DIALOG: 'DIALOG',

  // Gameplay Actions
  DROP_FANCY_RING: 'DROP_FANCY_RING',
  PICKUP_FANCY_RING: 'PICKUP_FANCY_RING',
};
